In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import tensorflow as tf

In [2]:
# Load data
file_path = "usa_co2_temp_1800_2013.csv"
predict_temp_df = pd.read_csv(file_path)
predict_temp_df.head(10)

,country,year,co2,co2_per_capita,cement_co2,cement_co2_per_capita,coal_co2,coal_co2_per_capita,flaring_co2,gas_co2,...,co2_per_gdp,methane,methane_per_capita,nitrous_oxide,nitrous_oxide_per_capita,population,gdp,energy_per_gdp,Avg Temperature,Avg Temperature Uncertainty
0,United States,1800,0.253,0.042,NaN,NaN,0.253,0.042,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6000000,NaN,NaN,12.377868,3.205628
1,United States,1801,0.267,0.044,NaN,NaN,0.267,0.044,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6113782,NaN,NaN,12.681863,2.895417
2,United States,1802,0.289,0.046,NaN,NaN,0.289,0.046,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6229723,NaN,NaN,12.859703,3.065703
3,United States,1803,0.297,0.047,NaN,NaN,0.297,0.047,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6347862,NaN,NaN,12.692603,3.065032
4,United States,1804,0.333,0.052,NaN,NaN,0.333,0.052,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6468241,NaN,NaN,12.576432,3.379515
5,United States,1805,0.341,0.052,NaN,NaN,0.341,0.052,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6590903,NaN,NaN,12.599647,3.106361
6,United States,1806,0.333,0.050,NaN,NaN,0.333,0.050,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6715891,NaN,NaN,12.048269,3.067562
7,United States,1807,0.377,0.055,NaN,NaN,0.377,0.055,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6843249,NaN,NaN,11.884543,3.124994
8,United States,1808,0.392,0.056,NaN,NaN,0.392,0.056,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6973023,NaN,NaN,11.949342,3.235417
9,United States,1809,0.403,0.057,NaN,NaN,0.403,0.057,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,7105258,NaN,NaN,11.329233,3.485137